package com.example.quizhuntercompose.cor.util

object TestTags {

    const val TITLE_TEXT_FIELD = "TITLE_TEXT_FIELD"
    const val QUESTION_ITEM = "QUESTION_ITEM"
    const val PICK_QUIZ_OPTIONS_ENABLER_BUTTON = "PICK_QUIZ_OPTIONS_ENABLER_BUTTON"
    const val PICK_QUIZ_OPTIONS_UNANSWERED_ROW = "PICK_QUIZ_OPTIONS_UNANSWERED_ROW"

    const val PICK_QUIZ_TEXT_VIEW_QUESTION_COUNT = "PICK_QUIZ_TEXT_VIEW_QUESTION_COUNT"
    const val PICK_QUIZ_SLIDER = "PICK_QUIZ_SLIDER"


}